import { Archive, Copy, Pencil, Plus, Search, Trash2 } from 'lucide-react'
import { useState } from 'react'
import { ImageUpload, Field, TextArea, TextInput, Toggle } from '../components/forms'
import { Button, ConfirmAction, EmptyState, ErrorState, LoadingBlock, Modal, PageHeader, SecondaryButton, StatusPill, useToast } from '../components/ui'
import { assetUrl } from '../lib/db'
import { errorMessage, formatCurrency } from '../lib/format'
import { getSupabase } from '../lib/supabase'
import type { Barber, Category, Service } from '../lib/types'
import { useAsyncData } from '../hooks/useAsync'
import { useDebouncedValue } from '../hooks/useDebouncedValue'

export function CategoriesPage() {
  const { pushToast } = useToast(); const [editing, setEditing] = useState<Category | null | 'new'>(null)
  const { data, loading, error, reload } = useAsyncData<Category[]>(async () => { const { data, error } = await getSupabase().from('categories').select('*').order('sort_order').order('name'); if (error) throw error; return data as Category[] }, [])
  const archive = async (category: Category) => { const { error } = await getSupabase().from('categories').update({ is_active: false, archived_at: new Date().toISOString() }).eq('id', category.id); if (error) { pushToast({ title: 'Kategoriyani arxivlab bo‘lmadi', message: errorMessage(error), tone: 'error' }); return }; pushToast({ title: 'Kategoriya arxivlandi', tone: 'success' }); void reload() }
  const remove = async (category: Category) => { const { error } = await getSupabase().from('categories').delete().eq('id', category.id); if (error) { pushToast({ title: 'Kategoriyani o‘chirib bo‘lmadi', message: errorMessage(error), tone: 'error' }); return }; pushToast({ title: 'Kategoriya o‘chirildi', tone: 'success' }); void reload() }
  return <><PageHeader title="Kategoriyalar" description="Xizmat katalogini qattiq kodlangan guruhlarsiz tartiblang." action={<Button onClick={() => setEditing('new')}><Plus size={17}/> Kategoriya qo‘shish</Button>}/>{loading ? <LoadingBlock/> : error || !data ? <ErrorState message={error ?? 'Kategoriyalarni yuklab bo‘lmadi.'} retry={() => void reload()}/> : <section className="management-grid">{data.map((category) => <article className="management-card" key={category.id}><div className="management-card-top">{category.image_path ? <img src={assetUrl(category.image_path)} alt=""/> : <span className="placeholder-image">{category.name.slice(0, 1)}</span>}<div><h3>{category.name}</h3><p>{category.description || 'Hozircha tavsif yo‘q.'}</p></div></div><div className="tag-row"><StatusPill value={category.archived_at ? 'archived' : category.is_active ? 'active' : 'inactive'}/><span>Tartib {category.sort_order}</span></div><div className="card-actions"><SecondaryButton onClick={() => setEditing(category)}><Pencil size={15}/> Tahrirlash</SecondaryButton><ConfirmAction title="Kategoriya arxivlansinmi?" description="Xizmatlar va tarixiy bronlar saqlanib qoladi. Kategoriyani keyinchalik qayta faollashtirishingiz mumkin." confirmLabel="Arxivlash" onConfirm={() => archive(category)}>{(open) => <button className="icon-button" onClick={open} title="Arxivlash"><Archive size={17}/></button>}</ConfirmAction><ConfirmAction title="Kategoriya o‘chirilsinmi?" description="Faqat hech qanday xizmat bu kategoriyaga havola qilmagan bo‘lsa, o‘chirish xavfsiz. Aks holda arxivlang." confirmLabel="O‘chirish" onConfirm={() => remove(category)}>{(open) => <button className="icon-button danger-text" onClick={open} title="O‘chirish"><Trash2 size={17}/></button>}</ConfirmAction></div></article>)}{!data.length && <EmptyState title="Hozircha kategoriyalar yo‘q" description="Katalog yaratishni boshlash uchun birinchi real kategoriyani qo‘shing." action={<Button onClick={() => setEditing('new')}>Kategoriya qo‘shish</Button>}/>}</section>}{editing && <CategoryForm category={editing === 'new' ? null : editing} onClose={() => setEditing(null)} onSaved={() => { setEditing(null); void reload() }}/>}</> 
}

function CategoryForm({ category, onClose, onSaved }: { category: Category | null; onClose: () => void; onSaved: () => void }) {
  const { pushToast } = useToast(); const [name, setName] = useState(category?.name ?? ''); const [description, setDescription] = useState(category?.description ?? ''); const [image, setImage] = useState<string | null>(category?.image_path ?? null); const [order, setOrder] = useState(String(category?.sort_order ?? 0)); const [active, setActive] = useState(category?.is_active ?? true); const [busy, setBusy] = useState(false)
  const save = async () => { if (!name.trim()) { pushToast({ title: 'Kategoriya nomi majburiy', tone: 'error' }); return }; setBusy(true); const payload = { name: name.trim(), description: description.trim() || null, image_path: image, sort_order: Number(order) || 0, is_active: active, archived_at: active ? null : category?.archived_at ?? new Date().toISOString() }; const query = category ? getSupabase().from('categories').update(payload).eq('id', category.id) : getSupabase().from('categories').insert(payload); const { error } = await query; setBusy(false); if (error) { pushToast({ title: 'Kategoriyani saqlab bo‘lmadi', message: errorMessage(error), tone: 'error' }); return }; pushToast({ title: category ? 'Kategoriya yangilandi' : 'Kategoriya yaratildi', tone: 'success' }); onSaved() }
  return <Modal title={category ? 'Kategoriyani tahrirlash' : 'Kategoriya qo‘shish'} onClose={onClose}><div className="form-grid"><Field label="Kategoriya nomi"><TextInput value={name} maxLength={100} onChange={(event) => setName(event.target.value)} autoFocus/></Field><Field label="Ko‘rsatish tartibi"><TextInput type="number" min="0" value={order} onChange={(event) => setOrder(event.target.value)}/></Field></div><Field label="Tavsif"><TextArea value={description} onChange={(event) => setDescription(event.target.value)} placeholder="Ixtiyoriy qisqa tavsif"/></Field><ImageUpload folder="services" label="Kategoriya rasmi" value={image} onChange={setImage}/><Toggle checked={active} onChange={setActive} label="Faol kategoriya" description="Nofaol kategoriyalar ommaviy katalog so‘rovlarida ko‘rinmaydi."/><div className="form-actions"><SecondaryButton onClick={onClose}>Bekor qilish</SecondaryButton><Button disabled={busy} onClick={() => void save()}>{busy ? 'Saqlanmoqda…' : 'Kategoriyani saqlash'}</Button></div></Modal>
}

export function ServicesPage() {
  const { pushToast } = useToast()
  const [editing, setEditing] = useState<Service | null | 'new'>(null)
  const [search, setSearch] = useState('')
  const debounced = useDebouncedValue(search)
  const { data, loading, error, reload } = useAsyncData<{ services: Service[]; categories: Category[]; barbers: Barber[] }>(async () => {
    const client = getSupabase()
    let serviceQuery = client.from('services').select('*, categories(name)').order('sort_order').order('name')
    if (debounced.trim()) serviceQuery = serviceQuery.ilike('name', `%${debounced.trim().replace(/[%_]/g, '')}%`)
    const [services, categories, barbers] = await Promise.all([
      serviceQuery.range(0, 99),
      client.from('categories').select('*').order('sort_order').order('name').limit(100),
      client.from('barbers').select('*').order('sort_order').order('name').limit(100),
    ])
    for (const result of [services, categories, barbers]) if (result.error) throw result.error
    return { services: services.data as Service[], categories: categories.data as Category[], barbers: barbers.data as Barber[] }
  }, [debounced])
  const archive = async (service: Service) => {
    const { error } = await getSupabase().from('services').update({ is_active: false, archived_at: new Date().toISOString() }).eq('id', service.id)
    if (error) { pushToast({ title: 'Xizmatni arxivlab bo‘lmadi', message: errorMessage(error), tone: 'error' }); return }
    pushToast({ title: 'Xizmat arxivlandi', tone: 'success' }); void reload()
  }
  const duplicate = async (service: Service) => {
    const { id, categories, ...source } = service
    const { error } = await getSupabase().from('services').insert({ ...source, name: `${service.name} nusxa`, is_active: false, archived_at: null })
    if (error) { pushToast({ title: 'Xizmatni nusxalab bo‘lmadi', message: errorMessage(error), tone: 'error' }); return }
    pushToast({ title: 'Xizmat nofaol holatda nusxalandi', tone: 'success' }); void reload()
  }
  return <>
    <PageHeader title="Xizmatlar" description="Narxlar, davomiyliklar, kategoriyalar, media va sartarosh birikmalari ma’lumotlar bazasidan olinadi." action={<Button onClick={() => setEditing('new')}><Plus size={17}/> Xizmat qo‘shish</Button>}/>
    <section className="filter-panel compact-filter"><Field label="Xizmatlarni qidirish"><span className="input-with-icon"><Search size={16}/><TextInput placeholder="Xizmat nomini qidirish" value={search} onChange={(event) => setSearch(event.target.value)}/></span></Field></section>
    {loading ? <LoadingBlock/> : error || !data ? <ErrorState message={error ?? 'Xizmatlarni yuklab bo‘lmadi.'} retry={() => void reload()}/> : <>
      <section className="management-grid">{data.services.map((service) => <article className="management-card" key={service.id}><div className="management-card-top">{service.image_path ? <img src={assetUrl(service.image_path)} alt=""/> : <span className="placeholder-image">✦</span>}<div><h3>{service.name}</h3><p>{service.categories?.name || 'Kategoriyasiz'} · {service.duration_minutes} daq</p></div></div><strong className="price-line">{formatCurrency(service.price, service.currency)}</strong><div className="tag-row"><StatusPill value={service.archived_at ? 'archived' : service.is_active ? 'active' : 'inactive'}/>{service.is_popular && <span>Ommabop</span>}{service.consultation_only && <span>Konsultatsiya</span>}</div><div className="card-actions"><SecondaryButton onClick={() => setEditing(service)}><Pencil size={15}/> Tahrirlash</SecondaryButton><button className="icon-button" onClick={() => void duplicate(service)} title="Xizmatni nusxalash"><Copy size={17}/></button><ConfirmAction title="Xizmat arxivlansinmi?" description="Tarixiy bron elementlari o‘z nusxasini saqlaydi. Arxivlangan xizmatlarni ommaviy bron qilib bo‘lmaydi." confirmLabel="Arxivlash" onConfirm={() => archive(service)}>{(open) => <button className="icon-button" onClick={open}><Archive size={17}/></button>}</ConfirmAction></div></article>)}</section>
      {!data.services.length && <EmptyState title="Xizmatlar topilmadi" description="Boshqa qidiruvni sinab ko‘ring yoki birinchi real xizmatni qo‘shing." action={<Button onClick={() => setEditing('new')}>Xizmat qo‘shish</Button>}/>} 
      {editing && <ServiceForm service={editing === 'new' ? null : editing} categories={data.categories} barbers={data.barbers} onClose={() => setEditing(null)} onSaved={() => { setEditing(null); void reload() }}/>} 
    </>}
  </>
}

function ServiceForm({ service, categories, barbers, onClose, onSaved }: { service: Service | null; categories: Category[]; barbers: Barber[]; onClose: () => void; onSaved: () => void }) {
  const { pushToast } = useToast(); const [name, setName] = useState(service?.name ?? ''); const [categoryId, setCategoryId] = useState(service?.category_id ?? categories.find((item) => item.is_active && !item.archived_at)?.id ?? ''); const [description, setDescription] = useState(service?.description ?? ''); const [price, setPrice] = useState(String(service?.price ?? '')); const [currency, setCurrency] = useState(service?.currency ?? ''); const [duration, setDuration] = useState(service ? String(service.duration_minutes) : ''); const [image, setImage] = useState<string | null>(service?.image_path ?? null); const [order, setOrder] = useState(String(service?.sort_order ?? 0)); const [active, setActive] = useState(service?.is_active ?? true); const [popular, setPopular] = useState(service?.is_popular ?? false); const [consultation, setConsultation] = useState(service?.consultation_only ?? false); const [barberIds, setBarberIds] = useState<string[]>([]); const [busy, setBusy] = useState(false)
  useAsyncData(async () => { if (!service) return []; const { data, error } = await getSupabase().from('barber_services').select('barber_id').eq('service_id', service.id); if (error) throw error; setBarberIds((data ?? []).map((item: { barber_id: string }) => item.barber_id)); return data ?? [] }, [service?.id])
  const save = async () => { if (!name.trim() || !categoryId || !currency.match(/^[A-Za-z]{3}$/) || Number(price) < 0 || !Number.isFinite(Number(price)) || Number(duration) <= 0) { pushToast({ title: 'Majburiy maydonlarni tekshiring', message: 'Nom, kategoriya, uch harfli valyuta, to‘g‘ri manfiy bo‘lmagan narx va davomiylikni kiriting.', tone: 'error' }); return }; setBusy(true); const payload = { name: name.trim(), category_id: categoryId, description: description.trim() || null, price: Number(price), currency: currency.toUpperCase(), duration_minutes: Number(duration), image_path: image, sort_order: Number(order) || 0, is_active: active, is_popular: popular, consultation_only: consultation, archived_at: active ? null : service?.archived_at ?? new Date().toISOString() }; let serviceId = service?.id; const result = service ? await getSupabase().from('services').update(payload).eq('id', service.id).select('id').single() : await getSupabase().from('services').insert(payload).select('id').single(); if (result.error || !result.data) { setBusy(false); pushToast({ title: 'Xizmatni saqlab bo‘lmadi', message: errorMessage(result.error), tone: 'error' }); return }; serviceId = (result.data as { id: string }).id; const client = getSupabase(); const remove = await client.from('barber_services').delete().eq('service_id', serviceId); if (!remove.error && barberIds.length) { const insert = await client.from('barber_services').insert(barberIds.map((barber_id) => ({ barber_id, service_id: serviceId, is_active: true }))); if (insert.error) { setBusy(false); pushToast({ title: 'Xizmat saqlandi, ammo sartaroshlarga biriktirish amalga oshmadi', message: errorMessage(insert.error), tone: 'error' }); return } } setBusy(false); pushToast({ title: service ? 'Xizmat yangilandi' : 'Xizmat yaratildi', tone: 'success' }); onSaved() }
  const toggle = (id: string) => setBarberIds((current) => current.includes(id) ? current.filter((item) => item !== id) : [...current, id])
  return <Modal title={service ? 'Xizmatni tahrirlash' : 'Xizmat qo‘shish'} onClose={onClose} wide><div className="form-grid"><Field label="Xizmat nomi"><TextInput value={name} onChange={(event) => setName(event.target.value)} autoFocus/></Field><Field label="Kategoriya"><select className="input" value={categoryId} onChange={(event) => setCategoryId(event.target.value)}><option value="">Kategoriya tanlang</option>{categories.filter((category) => category.is_active && !category.archived_at).map((category) => <option key={category.id} value={category.id}>{category.name}</option>)}</select></Field><Field label="Narx"><TextInput inputMode="decimal" type="number" min="0" step="0.01" value={price} onChange={(event) => setPrice(event.target.value)}/></Field><Field label="Valyuta"><TextInput maxLength={3} placeholder="3 harfli kod" value={currency} onChange={(event) => setCurrency(event.target.value.toUpperCase())}/></Field><Field label="Davomiylik (daqiqa)"><TextInput type="number" min="1" value={duration} onChange={(event) => setDuration(event.target.value)}/></Field><Field label="Ko‘rsatish tartibi"><TextInput type="number" min="0" value={order} onChange={(event) => setOrder(event.target.value)}/></Field></div><Field label="Tavsif"><TextArea value={description} onChange={(event) => setDescription(event.target.value)} placeholder="Bu xizmat nimalarni o‘z ichiga olishini yozing"/></Field><ImageUpload folder="services" value={image} onChange={setImage}/><div className="toggle-grid"><Toggle checked={active} onChange={setActive} label="Faol" description="Ommaviy bronlashda mavjud."/><Toggle checked={popular} onChange={setPopular} label="Ommabop" description="Bu xizmatni ajratib ko‘rsatish."/><Toggle checked={consultation} onChange={setConsultation} label="Faqat konsultatsiya" description="Konsultatsiya oqimi uchun belgilang."/></div><Field label="Mavjud sartaroshlar" hint="Faqat biriktirilgan faol sartarosh-xizmat juftliklari bron qilinishi mumkin."><div className="check-list multi-column">{barbers.filter((barber) => barber.is_active && !barber.archived_at).map((barber) => <label key={barber.id}><input type="checkbox" checked={barberIds.includes(barber.id)} onChange={() => toggle(barber.id)}/><span>{barber.name}</span></label>)}</div></Field><div className="form-actions"><SecondaryButton onClick={onClose}>Bekor qilish</SecondaryButton><Button disabled={busy} onClick={() => void save()}>{busy ? 'Saqlanmoqda…' : 'Xizmatni saqlash'}</Button></div></Modal>
}

export function BarbersPage() {
  const { pushToast } = useToast()
  const [editing, setEditing] = useState<Barber | null | 'new'>(null)
  const [search, setSearch] = useState('')
  const debounced = useDebouncedValue(search)
  const { data, loading, error, reload } = useAsyncData<{ barbers: Barber[]; services: Service[] }>(async () => {
    const client = getSupabase()
    let barberQuery = client.from('barbers').select('*').order('sort_order').order('name')
    if (debounced.trim()) barberQuery = barberQuery.ilike('name', `%${debounced.trim().replace(/[%_]/g, '')}%`)
    const [barbers, services] = await Promise.all([barberQuery.range(0, 99), client.from('services').select('*').order('sort_order').order('name').limit(100)])
    if (barbers.error) throw barbers.error
    if (services.error) throw services.error
    return { barbers: barbers.data as Barber[], services: services.data as Service[] }
  }, [debounced])
  const archive = async (barber: Barber) => {
    const { error } = await getSupabase().from('barbers').update({ is_active: false, archived_at: new Date().toISOString() }).eq('id', barber.id)
    if (error) { pushToast({ title: 'Sartaroshni arxivlab bo‘lmadi', message: errorMessage(error), tone: 'error' }); return }
    pushToast({ title: 'Sartarosh arxivlandi', tone: 'success' }); void reload()
  }
  return <>
    <PageHeader title="Sartaroshlar" description="Sartarosh profillari, mutaxassis xizmatlari va jadvallarini bir joydan boshqaring." action={<Button onClick={() => setEditing('new')}><Plus size={17}/> Sartarosh qo‘shish</Button>}/>
    <section className="filter-panel compact-filter"><Field label="Sartaroshlarni qidirish"><span className="input-with-icon"><Search size={16}/><TextInput placeholder="Sartarosh nomini qidirish" value={search} onChange={(event) => setSearch(event.target.value)}/></span></Field></section>
    {loading ? <LoadingBlock/> : error || !data ? <ErrorState message={error ?? 'Sartaroshlarni yuklab bo‘lmadi.'} retry={() => void reload()}/> : <>
      <section className="management-grid">{data.barbers.map((barber) => <article className="management-card" key={barber.id}><div className="management-card-top">{barber.profile_image_path ? <img src={assetUrl(barber.profile_image_path)} alt=""/> : <span className="placeholder-image">{barber.name.slice(0, 1)}</span>}<div><h3>{barber.name}</h3><p>{barber.position || 'Lavozim ko‘rsatilmagan'}</p></div></div><p className="clamp-copy">{barber.bio || 'Hozircha biografiya yo‘q.'}</p><div className="tag-row"><StatusPill value={barber.archived_at ? 'archived' : barber.is_active ? 'active' : 'inactive'}/>{barber.specialties.map((specialty) => <span key={specialty}>{specialty}</span>)}</div><div className="card-actions"><SecondaryButton onClick={() => setEditing(barber)}><Pencil size={15}/> Tahrirlash</SecondaryButton><ConfirmAction title="Sartarosh arxivlansinmi?" description="Mavjud bron tarixi saqlanadi. Sartarosh yangi ommaviy bronlardan olib tashlanadi." confirmLabel="Arxivlash" onConfirm={() => archive(barber)}>{(open) => <button className="icon-button" onClick={open}><Archive size={17}/></button>}</ConfirmAction></div></article>)}</section>
      {!data.barbers.length && <EmptyState title="Sartaroshlar topilmadi" description="Boshqa qidiruvni sinab ko‘ring yoki sartarosh qo‘shing, xizmatlarni biriktiring va jadvalni sozlang." action={<Button onClick={() => setEditing('new')}>Sartarosh qo‘shish</Button>}/>} 
      {editing && <BarberForm barber={editing === 'new' ? null : editing} services={data.services} onClose={() => setEditing(null)} onSaved={() => { setEditing(null); void reload() }}/>} 
    </>}
  </>
}

function BarberForm({ barber, services, onClose, onSaved }: { barber: Barber | null; services: Service[]; onClose: () => void; onSaved: () => void }) {
  const { pushToast } = useToast(); const [name, setName] = useState(barber?.name ?? ''); const [position, setPosition] = useState(barber?.position ?? ''); const [bio, setBio] = useState(barber?.bio ?? ''); const [photo, setPhoto] = useState<string | null>(barber?.profile_image_path ?? null); const [specialties, setSpecialties] = useState(barber?.specialties.join(', ') ?? ''); const [order, setOrder] = useState(String(barber?.sort_order ?? 0)); const [active, setActive] = useState(barber?.is_active ?? true); const [serviceIds, setServiceIds] = useState<string[]>([]); const [busy, setBusy] = useState(false)
  useAsyncData(async () => { if (!barber) return []; const { data, error } = await getSupabase().from('barber_services').select('service_id').eq('barber_id', barber.id); if (error) throw error; setServiceIds((data ?? []).map((item: { service_id: string }) => item.service_id)); return data ?? [] }, [barber?.id])
  const save = async () => { if (!name.trim()) { pushToast({ title: 'Sartarosh nomi majburiy', tone: 'error' }); return }; setBusy(true); const payload = { name: name.trim(), position: position.trim() || null, bio: bio.trim() || null, profile_image_path: photo, specialties: specialties.split(',').map((item) => item.trim()).filter(Boolean), sort_order: Number(order) || 0, is_active: active, archived_at: active ? null : barber?.archived_at ?? new Date().toISOString() }; const result = barber ? await getSupabase().from('barbers').update(payload).eq('id', barber.id).select('id').single() : await getSupabase().from('barbers').insert(payload).select('id').single(); if (result.error || !result.data) { setBusy(false); pushToast({ title: 'Sartaroshni saqlab bo‘lmadi', message: errorMessage(result.error), tone: 'error' }); return }; const barberId = (result.data as { id: string }).id; const client = getSupabase(); const removed = await client.from('barber_services').delete().eq('barber_id', barberId); if (!removed.error && serviceIds.length) { const inserted = await client.from('barber_services').insert(serviceIds.map((service_id) => ({ barber_id: barberId, service_id, is_active: true }))); if (inserted.error) { setBusy(false); pushToast({ title: 'Sartarosh saqlandi, ammo xizmat biriktirish amalga oshmadi', message: errorMessage(inserted.error), tone: 'error' }); return } } setBusy(false); pushToast({ title: barber ? 'Sartarosh yangilandi' : 'Sartarosh muvaffaqiyatli yaratildi.', tone: 'success' }); onSaved() }
  const toggle = (id: string) => setServiceIds((current) => current.includes(id) ? current.filter((item) => item !== id) : [...current, id])
  return <Modal title={barber ? 'Sartaroshni tahrirlash' : 'Sartarosh qo‘shish'} onClose={onClose} wide><div className="form-grid"><Field label="Sartarosh nomi"><TextInput value={name} autoFocus onChange={(event) => setName(event.target.value)}/></Field><Field label="Lavozim"><TextInput value={position} placeholder="Ixtiyoriy lavozim yoki unvon" onChange={(event) => setPosition(event.target.value)}/></Field><Field label="Ko‘rsatish tartibi"><TextInput type="number" min="0" value={order} onChange={(event) => setOrder(event.target.value)}/></Field></div><ImageUpload folder="barbers" label="Profil rasmi" value={photo} onChange={setPhoto}/><Field label="Biografiya"><TextArea value={bio} onChange={(event) => setBio(event.target.value)} placeholder="Qisqa professional taqdimot"/></Field><Field label="Ixtisosliklar" hint="Har bir ixtisoslikni vergul bilan ajrating."><TextInput value={specialties} onChange={(event) => setSpecialties(event.target.value)} placeholder="Masalan: aniq ish, stilistika"/></Field><Toggle checked={active} onChange={setActive} label="Faol sartarosh" description="Nofaol sartaroshlar yangi ommaviy bronlar uchun mavjud emas."/><Field label="Xizmatlar"><div className="check-list multi-column">{services.filter((service) => service.is_active && !service.archived_at).map((service) => <label key={service.id}><input type="checkbox" checked={serviceIds.includes(service.id)} onChange={() => toggle(service.id)}/><span>{service.name}</span><small>{service.duration_minutes} daq</small></label>)}</div></Field><div className="form-actions"><SecondaryButton onClick={onClose}>Bekor qilish</SecondaryButton><Button disabled={busy} onClick={() => void save()}>{busy ? 'Saqlanmoqda…' : 'Sartaroshni saqlash'}</Button></div></Modal>
}
