import { Archive, Copy, Pencil, Plus, Search, Trash2 } from 'lucide-react'
import { useState } from 'react'
import { ImageUpload, Field, TextArea, TextInput, Toggle } from '../components/forms'
import { Button, ConfirmAction, EmptyState, ErrorState, LoadingBlock, Modal, PageHeader, SecondaryButton, StatusPill, useToast } from '../components/ui'
import { assetUrl } from '../lib/db'
import { errorMessage, formatCurrency } from '../lib/format'
import { getSupabase } from '../lib/supabase'
import type { Barber, Category, Service } from '../lib/types'
import { useAsyncData } from '../hooks/useAsync'
import { useDebouncedValue } from '../hooks/useDebouncedValue'

export function CategoriesPage() {
  const { pushToast } = useToast(); const [editing, setEditing] = useState<Category | null | 'new'>(null)
  const { data, loading, error, reload } = useAsyncData<Category[]>(async () => { const { data, error } = await getSupabase().from('categories').select('*').order('sort_order').order('name'); if (error) throw error; return data as Category[] }, [])
  const archive = async (category: Category) => { const { error } = await getSupabase().from('categories').update({ is_active: false, archived_at: new Date().toISOString() }).eq('id', category.id); if (error) { pushToast({ title: 'Could not archive category', message: errorMessage(error), tone: 'error' }); return }; pushToast({ title: 'Category archived', tone: 'success' }); void reload() }
  const remove = async (category: Category) => { const { error } = await getSupabase().from('categories').delete().eq('id', category.id); if (error) { pushToast({ title: 'Cannot delete category', message: errorMessage(error), tone: 'error' }); return }; pushToast({ title: 'Category deleted', tone: 'success' }); void reload() }
  return <><PageHeader title="Categories" description="Organize the service catalogue without hardcoded frontend groups." action={<Button onClick={() => setEditing('new')}><Plus size={17}/> Add category</Button>}/>{loading ? <LoadingBlock/> : error || !data ? <ErrorState message={error ?? 'Unable to load categories.'} retry={() => void reload()}/> : <section className="management-grid">{data.map((category) => <article className="management-card" key={category.id}><div className="management-card-top">{category.image_path ? <img src={assetUrl(category.image_path)} alt=""/> : <span className="placeholder-image">{category.name.slice(0, 1)}</span>}<div><h3>{category.name}</h3><p>{category.description || 'No description yet.'}</p></div></div><div className="tag-row"><StatusPill value={category.archived_at ? 'archived' : category.is_active ? 'active' : 'inactive'}/><span>Order {category.sort_order}</span></div><div className="card-actions"><SecondaryButton onClick={() => setEditing(category)}><Pencil size={15}/> Edit</SecondaryButton><ConfirmAction title="Archive category?" description="Services and historical bookings remain intact. You can reactivate this category later." confirmLabel="Archive" onConfirm={() => archive(category)}>{(open) => <button className="icon-button" onClick={open} title="Archive"><Archive size={17}/></button>}</ConfirmAction><ConfirmAction title="Delete category?" description="Deletion is only safe when no services reference this category. Otherwise archive it." confirmLabel="Delete" onConfirm={() => remove(category)}>{(open) => <button className="icon-button danger-text" onClick={open} title="Delete"><Trash2 size={17}/></button>}</ConfirmAction></div></article>)}{!data.length && <EmptyState title="No categories yet" description="Create your first real service category to begin building the catalogue." action={<Button onClick={() => setEditing('new')}>Add category</Button>}/>}</section>}{editing && <CategoryForm category={editing === 'new' ? null : editing} onClose={() => setEditing(null)} onSaved={() => { setEditing(null); void reload() }}/>}</> 
}

function CategoryForm({ category, onClose, onSaved }: { category: Category | null; onClose: () => void; onSaved: () => void }) {
  const { pushToast } = useToast(); const [name, setName] = useState(category?.name ?? ''); const [description, setDescription] = useState(category?.description ?? ''); const [image, setImage] = useState<string | null>(category?.image_path ?? null); const [order, setOrder] = useState(String(category?.sort_order ?? 0)); const [active, setActive] = useState(category?.is_active ?? true); const [busy, setBusy] = useState(false)
  const save = async () => { if (!name.trim()) { pushToast({ title: 'Category name is required', tone: 'error' }); return }; setBusy(true); const payload = { name: name.trim(), description: description.trim() || null, image_path: image, sort_order: Number(order) || 0, is_active: active, archived_at: active ? null : category?.archived_at ?? new Date().toISOString() }; const query = category ? getSupabase().from('categories').update(payload).eq('id', category.id) : getSupabase().from('categories').insert(payload); const { error } = await query; setBusy(false); if (error) { pushToast({ title: 'Could not save category', message: errorMessage(error), tone: 'error' }); return }; pushToast({ title: category ? 'Category updated' : 'Category created', tone: 'success' }); onSaved() }
  return <Modal title={category ? 'Edit category' : 'Add category'} onClose={onClose}><div className="form-grid"><Field label="Category name"><TextInput value={name} maxLength={100} onChange={(event) => setName(event.target.value)} autoFocus/></Field><Field label="Display order"><TextInput type="number" min="0" value={order} onChange={(event) => setOrder(event.target.value)}/></Field></div><Field label="Description"><TextArea value={description} onChange={(event) => setDescription(event.target.value)} placeholder="Optional short description"/></Field><ImageUpload folder="services" label="Category image" value={image} onChange={setImage}/><Toggle checked={active} onChange={setActive} label="Active category" description="Inactive categories are hidden from public catalogue queries."/><div className="form-actions"><SecondaryButton onClick={onClose}>Cancel</SecondaryButton><Button disabled={busy} onClick={() => void save()}>{busy ? 'Saving…' : 'Save category'}</Button></div></Modal>
}

export function ServicesPage() {
  const { pushToast } = useToast()
  const [editing, setEditing] = useState<Service | null | 'new'>(null)
  const [search, setSearch] = useState('')
  const debounced = useDebouncedValue(search)
  const { data, loading, error, reload } = useAsyncData<{ services: Service[]; categories: Category[]; barbers: Barber[] }>(async () => {
    const client = getSupabase()
    let serviceQuery = client.from('services').select('*, categories(name)').order('sort_order').order('name')
    if (debounced.trim()) serviceQuery = serviceQuery.ilike('name', `%${debounced.trim().replace(/[%_]/g, '')}%`)
    const [services, categories, barbers] = await Promise.all([
      serviceQuery.range(0, 99),
      client.from('categories').select('*').order('sort_order').order('name').limit(100),
      client.from('barbers').select('*').order('sort_order').order('name').limit(100),
    ])
    for (const result of [services, categories, barbers]) if (result.error) throw result.error
    return { services: services.data as Service[], categories: categories.data as Category[], barbers: barbers.data as Barber[] }
  }, [debounced])
  const archive = async (service: Service) => {
    const { error } = await getSupabase().from('services').update({ is_active: false, archived_at: new Date().toISOString() }).eq('id', service.id)
    if (error) { pushToast({ title: 'Could not archive service', message: errorMessage(error), tone: 'error' }); return }
    pushToast({ title: 'Service archived', tone: 'success' }); void reload()
  }
  const duplicate = async (service: Service) => {
    const { id, categories, ...source } = service
    const { error } = await getSupabase().from('services').insert({ ...source, name: `${service.name} copy`, is_active: false, archived_at: null })
    if (error) { pushToast({ title: 'Could not duplicate service', message: errorMessage(error), tone: 'error' }); return }
    pushToast({ title: 'Service duplicated as inactive', tone: 'success' }); void reload()
  }
  return <>
    <PageHeader title="Services" description="Prices, durations, categories, media, and barber assignments all come from the database." action={<Button onClick={() => setEditing('new')}><Plus size={17}/> Add service</Button>}/>
    <section className="filter-panel compact-filter"><Field label="Search services"><span className="input-with-icon"><Search size={16}/><TextInput placeholder="Search service name" value={search} onChange={(event) => setSearch(event.target.value)}/></span></Field></section>
    {loading ? <LoadingBlock/> : error || !data ? <ErrorState message={error ?? 'Unable to load services.'} retry={() => void reload()}/> : <>
      <section className="management-grid">{data.services.map((service) => <article className="management-card" key={service.id}><div className="management-card-top">{service.image_path ? <img src={assetUrl(service.image_path)} alt=""/> : <span className="placeholder-image">✦</span>}<div><h3>{service.name}</h3><p>{service.categories?.name || 'Uncategorized'} · {service.duration_minutes} min</p></div></div><strong className="price-line">{formatCurrency(service.price, service.currency)}</strong><div className="tag-row"><StatusPill value={service.archived_at ? 'archived' : service.is_active ? 'active' : 'inactive'}/>{service.is_popular && <span>Popular</span>}{service.consultation_only && <span>Consultation</span>}</div><div className="card-actions"><SecondaryButton onClick={() => setEditing(service)}><Pencil size={15}/> Edit</SecondaryButton><button className="icon-button" onClick={() => void duplicate(service)} title="Duplicate service"><Copy size={17}/></button><ConfirmAction title="Archive service?" description="Historical booking items keep their snapshot. Archived services cannot be booked publicly." confirmLabel="Archive" onConfirm={() => archive(service)}>{(open) => <button className="icon-button" onClick={open}><Archive size={17}/></button>}</ConfirmAction></div></article>)}</section>
      {!data.services.length && <EmptyState title="No services found" description="Try another search or add the first real service." action={<Button onClick={() => setEditing('new')}>Add service</Button>}/>} 
      {editing && <ServiceForm service={editing === 'new' ? null : editing} categories={data.categories} barbers={data.barbers} onClose={() => setEditing(null)} onSaved={() => { setEditing(null); void reload() }}/>} 
    </>}
  </>
}

function ServiceForm({ service, categories, barbers, onClose, onSaved }: { service: Service | null; categories: Category[]; barbers: Barber[]; onClose: () => void; onSaved: () => void }) {
  const { pushToast } = useToast(); const [name, setName] = useState(service?.name ?? ''); const [categoryId, setCategoryId] = useState(service?.category_id ?? categories.find((item) => item.is_active && !item.archived_at)?.id ?? ''); const [description, setDescription] = useState(service?.description ?? ''); const [price, setPrice] = useState(String(service?.price ?? '')); const [currency, setCurrency] = useState(service?.currency ?? ''); const [duration, setDuration] = useState(service ? String(service.duration_minutes) : ''); const [image, setImage] = useState<string | null>(service?.image_path ?? null); const [order, setOrder] = useState(String(service?.sort_order ?? 0)); const [active, setActive] = useState(service?.is_active ?? true); const [popular, setPopular] = useState(service?.is_popular ?? false); const [consultation, setConsultation] = useState(service?.consultation_only ?? false); const [barberIds, setBarberIds] = useState<string[]>([]); const [busy, setBusy] = useState(false)
  useAsyncData(async () => { if (!service) return []; const { data, error } = await getSupabase().from('barber_services').select('barber_id').eq('service_id', service.id); if (error) throw error; setBarberIds((data ?? []).map((item: { barber_id: string }) => item.barber_id)); return data ?? [] }, [service?.id])
  const save = async () => { if (!name.trim() || !categoryId || !currency.match(/^[A-Za-z]{3}$/) || Number(price) < 0 || !Number.isFinite(Number(price)) || Number(duration) <= 0) { pushToast({ title: 'Check required fields', message: 'Enter a name, category, three-letter currency, valid non-negative price, and duration.', tone: 'error' }); return }; setBusy(true); const payload = { name: name.trim(), category_id: categoryId, description: description.trim() || null, price: Number(price), currency: currency.toUpperCase(), duration_minutes: Number(duration), image_path: image, sort_order: Number(order) || 0, is_active: active, is_popular: popular, consultation_only: consultation, archived_at: active ? null : service?.archived_at ?? new Date().toISOString() }; let serviceId = service?.id; const result = service ? await getSupabase().from('services').update(payload).eq('id', service.id).select('id').single() : await getSupabase().from('services').insert(payload).select('id').single(); if (result.error || !result.data) { setBusy(false); pushToast({ title: 'Could not save service', message: errorMessage(result.error), tone: 'error' }); return }; serviceId = (result.data as { id: string }).id; const client = getSupabase(); const remove = await client.from('barber_services').delete().eq('service_id', serviceId); if (!remove.error && barberIds.length) { const insert = await client.from('barber_services').insert(barberIds.map((barber_id) => ({ barber_id, service_id: serviceId, is_active: true }))); if (insert.error) { setBusy(false); pushToast({ title: 'Service saved, but barber assignments failed', message: errorMessage(insert.error), tone: 'error' }); return } } setBusy(false); pushToast({ title: service ? 'Service updated' : 'Service created', tone: 'success' }); onSaved() }
  const toggle = (id: string) => setBarberIds((current) => current.includes(id) ? current.filter((item) => item !== id) : [...current, id])
  return <Modal title={service ? 'Edit service' : 'Add service'} onClose={onClose} wide><div className="form-grid"><Field label="Service name"><TextInput value={name} onChange={(event) => setName(event.target.value)} autoFocus/></Field><Field label="Category"><select className="input" value={categoryId} onChange={(event) => setCategoryId(event.target.value)}><option value="">Choose category</option>{categories.filter((category) => category.is_active && !category.archived_at).map((category) => <option key={category.id} value={category.id}>{category.name}</option>)}</select></Field><Field label="Price"><TextInput inputMode="decimal" type="number" min="0" step="0.01" value={price} onChange={(event) => setPrice(event.target.value)}/></Field><Field label="Currency"><TextInput maxLength={3} placeholder="3-letter code" value={currency} onChange={(event) => setCurrency(event.target.value.toUpperCase())}/></Field><Field label="Duration (minutes)"><TextInput type="number" min="1" value={duration} onChange={(event) => setDuration(event.target.value)}/></Field><Field label="Display order"><TextInput type="number" min="0" value={order} onChange={(event) => setOrder(event.target.value)}/></Field></div><Field label="Description"><TextArea value={description} onChange={(event) => setDescription(event.target.value)} placeholder="Describe what this service includes"/></Field><ImageUpload folder="services" value={image} onChange={setImage}/><div className="toggle-grid"><Toggle checked={active} onChange={setActive} label="Active" description="Available in public booking."/><Toggle checked={popular} onChange={setPopular} label="Popular" description="Highlight this service."/><Toggle checked={consultation} onChange={setConsultation} label="Consultation only" description="Mark for consultation flow."/></div><Field label="Available barbers" hint="Only assigned active barber-service pairs can be booked."><div className="check-list multi-column">{barbers.filter((barber) => barber.is_active && !barber.archived_at).map((barber) => <label key={barber.id}><input type="checkbox" checked={barberIds.includes(barber.id)} onChange={() => toggle(barber.id)}/><span>{barber.name}</span></label>)}</div></Field><div className="form-actions"><SecondaryButton onClick={onClose}>Cancel</SecondaryButton><Button disabled={busy} onClick={() => void save()}>{busy ? 'Saving…' : 'Save service'}</Button></div></Modal>
}

export function BarbersPage() {
  const { pushToast } = useToast()
  const [editing, setEditing] = useState<Barber | null | 'new'>(null)
  const [search, setSearch] = useState('')
  const debounced = useDebouncedValue(search)
  const { data, loading, error, reload } = useAsyncData<{ barbers: Barber[]; services: Service[] }>(async () => {
    const client = getSupabase()
    let barberQuery = client.from('barbers').select('*').order('sort_order').order('name')
    if (debounced.trim()) barberQuery = barberQuery.ilike('name', `%${debounced.trim().replace(/[%_]/g, '')}%`)
    const [barbers, services] = await Promise.all([barberQuery.range(0, 99), client.from('services').select('*').order('sort_order').order('name').limit(100)])
    if (barbers.error) throw barbers.error
    if (services.error) throw services.error
    return { barbers: barbers.data as Barber[], services: services.data as Service[] }
  }, [debounced])
  const archive = async (barber: Barber) => {
    const { error } = await getSupabase().from('barbers').update({ is_active: false, archived_at: new Date().toISOString() }).eq('id', barber.id)
    if (error) { pushToast({ title: 'Could not archive barber', message: errorMessage(error), tone: 'error' }); return }
    pushToast({ title: 'Barber archived', tone: 'success' }); void reload()
  }
  return <>
    <PageHeader title="Barbers" description="Manage barber profiles, specialist services, and schedules from one place." action={<Button onClick={() => setEditing('new')}><Plus size={17}/> Add barber</Button>}/>
    <section className="filter-panel compact-filter"><Field label="Search barbers"><span className="input-with-icon"><Search size={16}/><TextInput placeholder="Search barber name" value={search} onChange={(event) => setSearch(event.target.value)}/></span></Field></section>
    {loading ? <LoadingBlock/> : error || !data ? <ErrorState message={error ?? 'Unable to load barbers.'} retry={() => void reload()}/> : <>
      <section className="management-grid">{data.barbers.map((barber) => <article className="management-card" key={barber.id}><div className="management-card-top">{barber.profile_image_path ? <img src={assetUrl(barber.profile_image_path)} alt=""/> : <span className="placeholder-image">{barber.name.slice(0, 1)}</span>}<div><h3>{barber.name}</h3><p>{barber.position || 'No position set'}</p></div></div><p className="clamp-copy">{barber.bio || 'No biography yet.'}</p><div className="tag-row"><StatusPill value={barber.archived_at ? 'archived' : barber.is_active ? 'active' : 'inactive'}/>{barber.specialties.map((specialty) => <span key={specialty}>{specialty}</span>)}</div><div className="card-actions"><SecondaryButton onClick={() => setEditing(barber)}><Pencil size={15}/> Edit</SecondaryButton><ConfirmAction title="Archive barber?" description="Existing booking history stays intact. The barber will be removed from new public bookings." confirmLabel="Archive" onConfirm={() => archive(barber)}>{(open) => <button className="icon-button" onClick={open}><Archive size={17}/></button>}</ConfirmAction></div></article>)}</section>
      {!data.barbers.length && <EmptyState title="No barbers found" description="Try another search or add a barber, assign services, then set a schedule." action={<Button onClick={() => setEditing('new')}>Add barber</Button>}/>} 
      {editing && <BarberForm barber={editing === 'new' ? null : editing} services={data.services} onClose={() => setEditing(null)} onSaved={() => { setEditing(null); void reload() }}/>} 
    </>}
  </>
}

function BarberForm({ barber, services, onClose, onSaved }: { barber: Barber | null; services: Service[]; onClose: () => void; onSaved: () => void }) {
  const { pushToast } = useToast(); const [name, setName] = useState(barber?.name ?? ''); const [position, setPosition] = useState(barber?.position ?? ''); const [bio, setBio] = useState(barber?.bio ?? ''); const [photo, setPhoto] = useState<string | null>(barber?.profile_image_path ?? null); const [specialties, setSpecialties] = useState(barber?.specialties.join(', ') ?? ''); const [order, setOrder] = useState(String(barber?.sort_order ?? 0)); const [active, setActive] = useState(barber?.is_active ?? true); const [serviceIds, setServiceIds] = useState<string[]>([]); const [busy, setBusy] = useState(false)
  useAsyncData(async () => { if (!barber) return []; const { data, error } = await getSupabase().from('barber_services').select('service_id').eq('barber_id', barber.id); if (error) throw error; setServiceIds((data ?? []).map((item: { service_id: string }) => item.service_id)); return data ?? [] }, [barber?.id])
  const save = async () => { if (!name.trim()) { pushToast({ title: 'Barber name is required', tone: 'error' }); return }; setBusy(true); const payload = { name: name.trim(), position: position.trim() || null, bio: bio.trim() || null, profile_image_path: photo, specialties: specialties.split(',').map((item) => item.trim()).filter(Boolean), sort_order: Number(order) || 0, is_active: active, archived_at: active ? null : barber?.archived_at ?? new Date().toISOString() }; const result = barber ? await getSupabase().from('barbers').update(payload).eq('id', barber.id).select('id').single() : await getSupabase().from('barbers').insert(payload).select('id').single(); if (result.error || !result.data) { setBusy(false); pushToast({ title: 'Could not save barber', message: errorMessage(result.error), tone: 'error' }); return }; const barberId = (result.data as { id: string }).id; const client = getSupabase(); const removed = await client.from('barber_services').delete().eq('barber_id', barberId); if (!removed.error && serviceIds.length) { const inserted = await client.from('barber_services').insert(serviceIds.map((service_id) => ({ barber_id: barberId, service_id, is_active: true }))); if (inserted.error) { setBusy(false); pushToast({ title: 'Barber saved, but service assignments failed', message: errorMessage(inserted.error), tone: 'error' }); return } } setBusy(false); pushToast({ title: barber ? 'Barber updated' : 'Barber created successfully.', tone: 'success' }); onSaved() }
  const toggle = (id: string) => setServiceIds((current) => current.includes(id) ? current.filter((item) => item !== id) : [...current, id])
  return <Modal title={barber ? 'Edit barber' : 'Add barber'} onClose={onClose} wide><div className="form-grid"><Field label="Barber name"><TextInput value={name} autoFocus onChange={(event) => setName(event.target.value)}/></Field><Field label="Position"><TextInput value={position} placeholder="Optional role or title" onChange={(event) => setPosition(event.target.value)}/></Field><Field label="Display order"><TextInput type="number" min="0" value={order} onChange={(event) => setOrder(event.target.value)}/></Field></div><ImageUpload folder="barbers" label="Profile photo" value={photo} onChange={setPhoto}/><Field label="Biography"><TextArea value={bio} onChange={(event) => setBio(event.target.value)} placeholder="Short professional introduction"/></Field><Field label="Specialties" hint="Separate each specialty with a comma."><TextInput value={specialties} onChange={(event) => setSpecialties(event.target.value)} placeholder="Example: precision work, styling"/></Field><Toggle checked={active} onChange={setActive} label="Active barber" description="Inactive barbers are not available for new public bookings."/><Field label="Services"><div className="check-list multi-column">{services.filter((service) => service.is_active && !service.archived_at).map((service) => <label key={service.id}><input type="checkbox" checked={serviceIds.includes(service.id)} onChange={() => toggle(service.id)}/><span>{service.name}</span><small>{service.duration_minutes} min</small></label>)}</div></Field><div className="form-actions"><SecondaryButton onClick={onClose}>Cancel</SecondaryButton><Button disabled={busy} onClick={() => void save()}>{busy ? 'Saving…' : 'Save barber'}</Button></div></Modal>
}
