import { Mail, MessageSquarePlus, Phone, Plus, Search, Trash2 } from 'lucide-react'
import { useState } from 'react'
import { Field, TextArea, TextInput } from '../components/forms'
import { Button, ConfirmAction, EmptyState, ErrorState, LoadingBlock, Modal, PageHeader, SecondaryButton, StatusPill, useToast } from '../components/ui'
import { dateInputValue, errorMessage, formatCurrency, formatDate, formatDateTime } from '../lib/format'
import { getSupabase } from '../lib/supabase'
import type { Booking, Customer, Review } from '../lib/types'
import { useAsyncData } from '../hooks/useAsync'
import { useDebouncedValue } from '../hooks/useDebouncedValue'

const PAGE_SIZE = 20
type CustomerSummary = { bookings: number; completed_bookings: number; cancelled_bookings: number; total_spending: number; last_visit: string | null; services: Array<{ name: string; uses: number }> }
type CustomerNote = { id: string; note: string; created_at: string }

export function CustomersPage() {
  const { pushToast } = useToast(); const [search, setSearch] = useState(''); const [page, setPage] = useState(0); const [selected, setSelected] = useState<Customer | null>(null); const [adding, setAdding] = useState(false); const debounced = useDebouncedValue(search)
  const { data, loading, error, reload } = useAsyncData<{ customers: Customer[]; total: number }>(async () => { const term = debounced.trim().replace(/[%_,]/g, ''); let query = getSupabase().from('customers').select('*', { count: 'exact' }).order('created_at', { ascending: false }); if (term) query = query.or(`full_name.ilike.%${term}%,phone.ilike.%${term}%,email.ilike.%${term}%`); const { data, error, count } = await query.range(page * PAGE_SIZE, (page + 1) * PAGE_SIZE - 1); if (error) throw error; return { customers: data as Customer[], total: count ?? 0 } }, [debounced, page])
  return <><PageHeader title="Mijozlar" description="Mijozlarning aloqa ma’lumotlari, bron tarixi, qiymati, sharhlari va xodimlarning shaxsiy izohlari." action={<Button onClick={() => setAdding(true)}><Plus size={17}/> Mijoz qo‘shish</Button>}/><section className="filter-panel compact-filter"><Field label="Mijozlarni qidirish"><span className="input-with-icon"><Search size={16}/><TextInput placeholder="Ism, telefon yoki email" value={search} onChange={(event) => { setSearch(event.target.value); setPage(0) }}/></span></Field></section>{loading ? <LoadingBlock/> : error || !data ? <ErrorState message={error ?? 'Mijozlarni yuklab bo‘lmadi.'} retry={() => void reload()}/> : <><section className="table-panel">{data.customers.length ? <div className="responsive-table customer-table"><div className="table-head"><span>Mijoz</span><span>Telefon</span><span>Email</span><span>Yaratilgan</span><span></span></div>{data.customers.map((customer) => <article className="table-row" key={customer.id}><div><strong>{customer.full_name}</strong></div><div>{customer.phone || '—'}</div><div className="truncate">{customer.email || '—'}</div><div>{formatDate(customer.created_at)}</div><button className="text-button" onClick={() => setSelected(customer)}>Profil</button></article>)}</div> : <EmptyState title="Mijozlar topilmadi" description="Mijoz yozuvlari bron orqali yaratiladi yoki xodimlar tomonidan qo‘shilishi mumkin." action={<Button onClick={() => setAdding(true)}>Mijoz qo‘shish</Button>}/>}</section><div className="pagination"><span>Jami {data.total} ta mijoz</span><div><SecondaryButton disabled={page === 0} onClick={() => setPage(page - 1)}>Oldingi</SecondaryButton><SecondaryButton disabled={(page + 1) * PAGE_SIZE >= data.total} onClick={() => setPage(page + 1)}>Keyingi</SecondaryButton></div></div>{selected && <CustomerDetail customer={selected} onClose={() => setSelected(null)}/>} {adding && <CustomerForm onClose={() => setAdding(false)} onSaved={() => { setAdding(false); pushToast({ title: 'Mijoz qo‘shildi', tone: 'success' }); void reload() }}/>}</>}</>
}

function CustomerForm({ onClose, onSaved }: { onClose: () => void; onSaved: () => void }) { const { pushToast } = useToast(); const [name, setName] = useState(''); const [phone, setPhone] = useState(''); const [email, setEmail] = useState(''); const [busy, setBusy] = useState(false); const save = async () => { if (!name.trim()) { pushToast({ title: 'Mijoz ismi majburiy', tone: 'error' }); return }; setBusy(true); const { error } = await getSupabase().from('customers').insert({ full_name: name.trim(), phone: phone.trim() || null, email: email.trim().toLowerCase() || null }); setBusy(false); if (error) { pushToast({ title: 'Mijozni qo‘shib bo‘lmadi', message: errorMessage(error), tone: 'error' }); return }; onSaved() }; return <Modal title="Mijoz qo‘shish" onClose={onClose}><div className="form-grid"><Field label="To‘liq ism"><TextInput value={name} onChange={(event) => setName(event.target.value)} autoFocus/></Field><Field label="Telefon"><TextInput value={phone} onChange={(event) => setPhone(event.target.value)}/></Field><Field label="Email"><TextInput type="email" value={email} onChange={(event) => setEmail(event.target.value)}/></Field></div><div className="form-actions"><SecondaryButton onClick={onClose}>Bekor qilish</SecondaryButton><Button disabled={busy} onClick={() => void save()}>{busy ? 'Saqlanmoqda…' : 'Mijoz qo‘shish'}</Button></div></Modal> }

function CustomerDetail({ customer, onClose }: { customer: Customer; onClose: () => void }) {
  const { pushToast } = useToast(); const [note, setNote] = useState(''); const [notesOpen, setNotesOpen] = useState(false)
  const { data, loading, error, reload } = useAsyncData<{ summary: CustomerSummary; bookings: Booking[]; notes: CustomerNote[]; reviews: Review[] }>(async () => { const client = getSupabase(); const [summary, bookings, notes, reviews] = await Promise.all([client.rpc('admin_customer_summary', { p_customer_id: customer.id }), client.from('bookings').select('*, barbers(name), booking_items(*)').eq('customer_id', customer.id).order('booking_date', { ascending: false }).range(0, 19), client.from('customer_notes').select('*').eq('customer_id', customer.id).order('created_at', { ascending: false }).range(0, 29), client.from('reviews').select('*').eq('customer_id', customer.id).order('created_at', { ascending: false }).range(0, 19)]); for (const result of [summary, bookings, notes, reviews]) if (result.error) throw result.error; return { summary: summary.data as CustomerSummary, bookings: bookings.data as Booking[], notes: notes.data as CustomerNote[], reviews: reviews.data as Review[] } }, [customer.id])
  const addNote = async () => { if (!note.trim()) return; const { error } = await getSupabase().from('customer_notes').insert({ customer_id: customer.id, note: note.trim() }); if (error) { pushToast({ title: 'Izohni saqlab bo‘lmadi', message: errorMessage(error), tone: 'error' }); return }; setNote(''); pushToast({ title: 'Ichki izoh qo‘shildi', tone: 'success' }); void reload() }
  const deleteNote = async (id: string) => { const { error } = await getSupabase().from('customer_notes').delete().eq('id', id); if (error) { pushToast({ title: 'Izohni o‘chirib bo‘lmadi', message: errorMessage(error), tone: 'error' }); return }; pushToast({ title: 'Izoh o‘chirildi', tone: 'success' }); void reload() }
  return <Modal title="Mijoz profili" onClose={onClose} wide><div className="customer-profile-header"><div><h3>{customer.full_name}</h3><p>{customer.phone && <><Phone size={14}/>{customer.phone}</>} {customer.email && <><Mail size={14}/>{customer.email}</>}</p></div><span>Mijoz ro‘yxatga olingan sana: {formatDate(customer.created_at)}</span></div>{loading ? <LoadingBlock/> : error || !data ? <ErrorState message={error ?? 'Mijoz tafsilotlarini yuklab bo‘lmadi.'} retry={() => void reload()}/> : <><div className="metric-strip"><Metric label="Bronlar" value={data.summary.bookings}/><Metric label="Yakunlangan" value={data.summary.completed_bookings}/><Metric label="Bekor qilingan" value={data.summary.cancelled_bookings}/><Metric label="Jami xarajat" value={formatCurrency(data.summary.total_spending)}/><Metric label="Oxirgi tashrif" value={formatDate(data.summary.last_visit)}/></div><div className="detail-section"><h3>So‘nggi bron tarixi</h3>{data.bookings.length ? data.bookings.map((booking) => <div className="compact-row" key={booking.id}><div><strong>{formatDate(booking.booking_date)} · {booking.barbers?.name || '—'}</strong><p>{booking.booking_items?.map((item) => item.service_name_snapshot).join(', ') || '—'}</p></div><strong>{formatCurrency(booking.total_amount, booking.currency)}</strong><StatusPill value={booking.status}/></div>) : <p className="muted">Bron tarixi yo‘q.</p>}</div><div className="detail-section"><h3>Ishlatilgan xizmatlar</h3><div className="tag-row">{data.summary.services.length ? data.summary.services.map((service) => <span key={service.name}>{service.name} · {service.uses}</span>) : <span>Yakunlangan xizmat tarixi yo‘q</span>}</div></div><div className="detail-section"><div className="section-inline-heading"><h3>Ichki izohlar</h3><span>Faqat vakolatli xodimlarga ko‘rinadi.</span></div><div className="note-composer"><TextArea value={note} onChange={(event) => setNote(event.target.value)} placeholder="Shaxsiy ish izohi qo‘shing"/><Button onClick={() => void addNote()}><MessageSquarePlus size={16}/> Izoh qo‘shish</Button></div>{data.notes.map((item) => <div className="note-entry" key={item.id}><p>{item.note}</p><small>{formatDateTime(item.created_at)}</small><ConfirmAction title="Ichki izoh o‘chirilsinmi?" description="Bu amalni ortga qaytarib bo‘lmaydi." confirmLabel="O‘chirish" onConfirm={() => deleteNote(item.id)}>{(open) => <button className="text-button danger-text" onClick={open}>O‘chirish</button>}</ConfirmAction></div>)}</div><div className="detail-section"><h3>Sharhlar</h3>{data.reviews.length ? data.reviews.map((review) => <div className="compact-row" key={review.id}><span className="rating-mark">{review.rating}★</span><p>{review.comment || 'Yozma izoh yo‘q'}</p><StatusPill value={review.status}/></div>) : <p className="muted">Sharhlar yuborilmagan.</p>}</div></>}</Modal>
}
function Metric({ label, value }: { label: string; value: string | number }) { return <div><span>{label}</span><strong>{value}</strong></div> }
